"""
Django settings for web_service project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

from os import path as os_path

import urllib3

import constants_settings
urllib3.disable_warnings()

# Build paths inside the project like this: os_path.join(BASE_DIR, ...)
BASE_DIR = os_path.dirname(os_path.dirname(os_path.abspath(__file__)))

X_FRAME_OPTIONS = 'ALLOWALL'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'w)!(g0oqqekypclv%0e2w8v@=h(5xskam=uu1cqs549=&zya(6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = constants_settings.WEB_SETTINGS_DEBUG
#DEBUG = constants.WEB_SETTINGS_DEBUG

ALLOWED_HOSTS = constants_settings.WEB_SETTINGS_ALLOWED_HOSTS

DOMAIN = constants_settings.WEB_SETTINGS_DOMAIN

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'captchas_upload',
    'account_spider_interface',
    'rest_api',
    'oauth2_provider',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'account_spider_interface.middleware.AccessTokenMiddleware',
]

ROOT_URLCONF = 'web_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os_path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'web_service.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = constants_settings.WEB_SETTINGS_DATABASES

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os_path.join(BASE_DIR, 'static'),
    # Put strings here, like "/home/html/static" or "C:/www/django/static".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.
)

if not DEBUG:
    STATIC_ROOT = os_path.join(BASE_DIR, 'static')

CAPTCHA_DIR = "captcha"

LOG_FILE = os_path.join("log", "django.log")

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s [%(asctime)s] (%(module)s) :  %(message)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'mail_admins': {
            'level': 'CRITICAL',
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': LOG_FILE,
            'formatter': 'simple'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'CRITICAL',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['file'],
            'level': 'CRITICAL',
            'propagate': False,
        },
        'captchas_upload': {
            'handlers': ['file'],
            'level': 'ERROR',
        },
        'account_spider_interface': {
            'handlers': ['file'],
            'level': 'ERROR',
        },
        'rest_api': {
            'handlers': ['file'],
            'level': 'ERROR',
        },
    }
}

CORS_ORIGIN_ALLOW_ALL = True

OAUTH2_PROVIDER = {
    "ACCESS_TOKEN_EXPIRE_SECONDS": 1800,
    "RESOURCE_SERVER_TOKEN_CACHING_SECONDS": 1800,
}

PRIVATE_KEY = """-----BEGIN RSA PRIVATE KEY-----
MIICXQIBAAKBgQCqQ9Fg9J7pVIbcdiX1hiATkc3jdEHaywEJQs4mbXo6OoJlfGiO
+n5/Gz3d/tMXjuW79lzMpXkC33TRY31/Cn8xGIFt23u1hGihW74JHdYNl3cU0Kc9
I+k/8Il3WmicxZz5B8nOqxLXbLhYAlovIiQXaXaq5KS6ckKdxhAZrGl3ZQIDAQAB
AoGAHoPyl/unqn5zgDotofQ0tgUs/x3EOsQk7qW6QFFhNWPsoGc8bxmuh7XYb/ve
leuOuZIVPjlO96iYbXm1EYqOUnFyN+5cXqoSez6cWfTrqz1vVihjL6EirjVWsbKG
f/TuNsh36TqViq/oe0M08/8mRdkdglZRVMMLRggQmBLhNTkCQQDAeuI98n5pQFVz
xB0suZHfA/cn4qBGTBJgY1AmnMJPleWvw6sfmBIXxPq6PYVESKC2cvpd0zqP3tX7
ZQrExQ8tAkEA4nQn234ygM0cF1L1bBfJ05U6iGwJeucPttkwNxw9VguHK4ZnfcDv
Lfdl8O6nsh6Xug1JMFkXN0wdX6xYuFRsGQJACS5TWE0WxoJxEQKLubRoRtDzmw1u
Q6whPEPAcPcNNaqauBWHNgyU4Fle9D82+hjUwZ8eXhdTNcWVQ1aAev5DSQJBANwx
T/Q4gIkHaBIx41wIwYIP78tpKcqs1HXaN+zOc8GwEe47kXQQ30EV97TPipZC8wvB
EXKGnnFxfHpkDhymUjkCQQCvIwa+jmSqNU2jfCJ2MUd39Qi5sA5pDOavd/9uli6q
M6u6kGQVDhIHcVOk1VLE1oaHm9Uwaeszlp0BA8SoDFj5
-----END RSA PRIVATE KEY-----"""
