# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaList',
            fields=[
                ('uid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=40)),
                ('result', models.CharField(blank=True, max_length=32, null=True)),
                ('website', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'captcha_list',
                'managed': False,
            },
        ),
    ]
